config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'

  get 'tweets/index' => 'tweets#index'

  resources :tweets, only: :index

 post '/tweets/save_tweets_to_database' => 'tweets#save_tweets_to_database', :as => 'save_tweets_to_database'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base

	#A method to grab latest tweets from a Twitter user
	# def self.get_tweets
		    
	# 	    #create a Twitter Search object
	# 	    search = Twitter::Search.new
		    
	# 	    #grab recent 10 tweets which contain 'new year resolution' words, and loop each of them
	# 	    search.containing("new year resolution").result_type("recent").per_page(10).fetch.each do |tweet_results|
		   
		      
 #        #creating the tweet record
 #        Tweet.create!({
 #            :username => tweet_results.username,
 #            :content => tweet_results.content,
 #            :created => twitter_created_at
 #        })
 #      end
 #    end
 #  end

 # attr_accessible :content, :username


		# def self.get_tweets
		# 	Twitter.user_timeline(params[:search]).each do |tweet|
		
		# 	    create({
			            
		# 	            content: tweet.text,
		# 	            username: tweet.screen_name}
		# 	    )
		# 	end
		# end

		# def self.save_tweets_into_database
		#     tweets = client.user_timeline(params[:search], options)
		#     tweets.each do |tweet|
		        
		#         Newtweets.create({content: tweet.text, username: tweet.user.screen_name})
		#         end
		#    end
		# end

		
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
	class TweetsController < ApplicationController
		
		def index
			require 'twitter'

			client = Twitter::REST::Client.new do |config|
				  config.consumer_key        = ENV['TWITTER_CONSUMER_KEY']
				  config.consumer_secret     = ENV['TWITTER_CONSUMER_SECRET']
				  config.access_token        = ENV['TWITTER_ACCESS_TOKEN']
				  config.access_token_secret = ENV['TWITTER_ACCESS_TOKEN_SECRET']
				end

			options = {:count => 10}

			@tweets = client.user_timeline(params[:search], options)
		     
			
		end

		
		def save_tweets_to_database

		require 'twitter'

			client = Twitter::REST::Client.new do |config|
				  config.consumer_key        = ENV['TWITTER_CONSUMER_KEY']
				  config.consumer_secret     = ENV['TWITTER_CONSUMER_SECRET']
				  config.access_token        = ENV['TWITTER_ACCESS_TOKEN']
				  config.access_token_secret = ENV['TWITTER_ACCESS_TOKEN_SECRET']
				end

			options = {:count => 10}
			@tweets = client.user_timeline(params[:search], options)

				Tweet.create(username: 'barackobama', content: 'saying this right now!')
				
			    @tweets.each do |t|
			       Tweet.create do |u|
				    u.username =  t.screen_name
				    u.content = t.text
			  		end
				end
		end
			  

		 
	end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_controller_helper.rb
module TweetsControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweety</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/index.html.erb
<div class="container-fluid">
			
              <%= form_tag tweets_path, :method => "get"  do %>
				    <%= label_tag :search, "Enter Twitter username :"  %>
				    <%= text_field_tag :search, params[:search] %>
				    <%= submit_tag "View Tweets", :name => nil %>
				    
			  <% end %>

			  <ul class='tweets'>
				<% @tweets.each do |t| %>
					<li><%= t.text %> created at <%= t.created_at %> by <%= t.user.screen_name %></li>
				<% end %>
			  </ul>
             

              <%= button_to 'Save Tweets', save_tweets_to_database_path %>
               
                     
               </script>
              
</div>